USE ClinicaDb

-- ORDEM DE CRIAÇÃO DAS TABELAS SEMPRE DAS PONTAS PARA O MIOLO DO MODELO
CREATE TABLE ESPECIALIDADE(
	ID_ESP INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(120) NOT NULL,
	CONSTRAINT UQ_NOME_ESPECIALIDADE UNIQUE (NOME)
);

CREATE TABLE PACIENTE(
	ID_PAC INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(120) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	CPF VARCHAR(11) NULL,
	CONSTRAINT CK_SEXO_PACIENTE CHECK (SEXO IN ('M', 'F')),
	CONSTRAINT UQ_CPF_PACIENTE UNIQUE (CPF)
);

CREATE TABLE MEDICO(
	CRM INT PRIMARY KEY,
	NOME VARCHAR(120) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	CONSTRAINT CK_SEXO_MEDICO CHECK (SEXO IN ('M', 'F'))
);

CREATE TABLE CONSULTA(
	ID_PAC INT, --CHAVE ESTRANGEIRA DE PACIENTE
	CRM INT, --CHAVE ESTRANEGEIRA DE MEDICO
	DATA_HORA_CONSULTA DATE, --OS 3 CAMPOS SERÃO PRIMARY KEYS
	TIPO_CONSULTA CHAR(1) NOT NULL, --PERMITE C-CONSULTA/R-RETORNO
	DESCRICAO_ATENDIMENTO VARCHAR(500) NULL, --DESCRICAO PERMITIRA NULL POIS AO INSERIR AINDA NÃO TEREMOS A DESCRICAO DO ATENDIMENTO
	CONSTRAINT CK_TIPO_CONSULTA_CONS CHECK (TIPO_CONSULTA IN ('C', 'R')),
	CONSTRAINT PK_CONSULTA PRIMARY KEY (ID_PAC, CRM, DATA_HORA_CONSULTA),
	CONSTRAINT FK_PAC_CONS FOREIGN KEY (ID_PAC) REFERENCES PACIENTE (ID_PAC),
	CONSTRAINT FK_MED_CONS FOREIGN KEY (CRM) REFERENCES MEDICO (CRM),
);



